# https://quarkus.io/guides/all-config

nsa.datagen=false

# https://docs.quarkiverse.io/quarkus-jdbc-sqlite/dev/index.html
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dbuser
quarkus.datasource.password=superSecret
quarkus.datasource.jdbc.url=jdbc:postgresql://nsa-db:5432/vulndb
quarkus.default-locale=en_US
quarkus.http.access-log.enabled=true
